# Generated by Django 6.0.6 on 2026-06-23 22:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('usuario', 'videojuego')},
        ),
    ]
